project:
  type: website

website:
  title: "My blog"
  navbar:
    left:
      - text: "Posts"
        file: index.qmd
      - text: "About me"
        file: about.qmd

    right:
      - icon: github
        href: https://github.com/andreeas26
      - icon: linkedin
        href: https://www.linkedin.com/in/andreea-elena-sandu/
format:
  html:
    theme: yeti
    css: styles.css



